@startuml
skinparam packageStyle rectangle

package "Aggregation" as Aggregation {
}
package "Configuration" as Configuration {
}
package "Framework" as Framework {
}
package "Logging" as Logging {
}
package "Synchronization" as Synchronization {
}
package "Utilities" as Utilities {
}

Aggregation ..> Logging : "instance()\nsetLogLevel()\ngetLogLevel()\nsetSink()"
Aggregation ..> Utilities : "joinHandler()\ngetInstance()\nsubscribeOnSigint()\nsubscribeOnExit()"
Configuration ..> Framework
Configuration ..> Logging : "instance()\nsetLogLevel()\ngetLogLevel()\nsetSink()"
Configuration ..> Utilities : "operator()\ndegrees()\nsetRad()\nfromRad()"
Framework ..> Aggregation : "add()\ngetOne()\ngetAll()\naggregate()"
Framework ..> Configuration : "params()\nsetParams()\nconfigure()\nparse()"
Framework ..> Logging : "instance()\nsetLogLevel()\ngetLogLevel()\nsetSink()"
Logging ..> Utilities : "now()\ntimeSinceStart()\nwaitFor()\nwaitUntil()"
Synchronization ..> Aggregation : "add()\ngetOne()\ngetAll()\naggregate()"
Synchronization ..> Logging : "instance()\nsetLogLevel()\ngetLogLevel()\nsetSink()"
Synchronization ..> Utilities : "getInstance()\ninitialize()\nconvert()\nbegin()"
Utilities ..> Aggregation : "notifyAggregationOnUpdate()\nget()\nisSet()\ncheckIsSet()"
Utilities ..> Configuration : "params()\nsetParams()\nconfigure()\nparse()"
Utilities ..> Framework : "static_assert()\ncreate()\ncreateType()\ncreateDefault()"
Utilities ..> Logging : "instance()\nsetLogLevel()\ngetLogLevel()\nsetSink()"
Utilities ..> Synchronization : "run()\nrunAllStages()"

'Generated by annotate_packages.py
@enduml