from __future__ import annotations

import csv
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[4]
TRACE_PATH = ROOT / "runtime_traces.txt"
CSV_PATH = ROOT / "sequence_dependency_table.csv"
QUERY_LOG_PATH = Path(__file__).resolve().parents[1] / "cypher_query.txt"


@dataclass
class TraceRow:
    timestamp: str
    event_name: str
    client_component: str
    client_function: str
    server_component: str
    server_function: str
    relationship_type: str


def _parse_timestamp(value: str) -> datetime:
    text = value.strip().replace("Z", "+00:00")
    return datetime.fromisoformat(text)


def _clean(value: str) -> str:
    return value.strip()


def main() -> int:
    if not TRACE_PATH.exists():
        raise SystemExit(f"Missing runtime trace log: {TRACE_PATH}")

    rows: list[TraceRow] = []
    with TRACE_PATH.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="|")
        for record in reader:
            rows.append(
                TraceRow(
                    timestamp=_clean(record.get("EventTimestamp", "")),
                    event_name=_clean(record.get("EventName", "")),
                    client_component=_clean(record.get("ClientComponent", "")),
                    client_function=_clean(record.get("ClientFunction", "")),
                    server_component=_clean(record.get("ServerComponent", "")),
                    server_function=_clean(record.get("ServerFunction", "")),
                    relationship_type=_clean(record.get("RelationshipType", "")),
                )
            )

    rows.sort(key=lambda row: (_parse_timestamp(row.timestamp), row.client_component, row.client_function, row.server_component, row.server_function, row.event_name))

    CSV_PATH.parent.mkdir(parents=True, exist_ok=True)
    with CSV_PATH.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "Sequence",
                "EventName",
                "ClientComponent",
                "ClientFunction",
                "ServerComponent",
                "ServerFunction",
                "RelationshipType",
                "EventTimestamp",
            ],
        )
        writer.writeheader()
        for index, row in enumerate(rows, start=1):
            writer.writerow(
                {
                    "Sequence": index,
                    "EventName": row.event_name,
                    "ClientComponent": row.client_component,
                    "ClientFunction": row.client_function,
                    "ServerComponent": row.server_component,
                    "ServerFunction": row.server_function,
                    "RelationshipType": row.relationship_type,
                    "EventTimestamp": row.timestamp,
                }
            )

    QUERY_LOG_PATH.write_text(
        "Input source: runtime_traces.txt generated by get-runtime-traces\nNo direct Neo4j query is executed by this skill.\n",
        encoding="utf-8",
    )

    print(f"Sequence rows written: {len(rows)}")
    print(f"Sequence table written to: {CSV_PATH}")
    print(f"Trace source note written to: {QUERY_LOG_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
